### ISSUE TITLE
i want to add badge processing with pytorch

### ISSUE THREAD

**Issue by apol-katsunori-kaai** [MKLab-ITI/visil#20]
Hi! Extract_features() has batch processing in tensorflow, but not in pytorch.
Is there somewhere I can specify badge handling? If not, please add it.

**Comment by gkordo** [comment]
Hi, and sorry for the late response.
The feature extraction process can not be implemented in the same way in PyTorch, because the entire video tensor and the internal representations are stored in GPU, irrespective of whether the processing is done in a batched manner, causing memory issues.

You can use the function [extract_features()](https://github.com/MKLab-ITI/visil/blob/5751de6d7fdd48098b35c694aa250f2f1dad6a9f/evaluation.py#L11) instead, to extract features in a batched way.
