### ISSUE TITLE
Large video database search

### ISSUE THREAD

**Issue by RostislavKorst** [MKLab-ITI/visil#22]
Hello!

Thank you very much for sharing this awesome implementation and the paper. I measured processing time on large database of videos (core VCDB) and it was slow. I was wondering, can we use vector search framework such as FAISS to increase search speed across database? But as I understood, there is a pairwise comparison between videos because of additional network for similarity calculation.

Thank you very much!

**Comment by gkordo** [comment]
@RostislavKorst, thanks for your question. Indeed, doing an exhaustive search and calculating all pairwise similarities between videos is very slow. This is what we tried to address in our follow-up [Distill-and-Select work](https://github.com/mever-team/distill-and-select), so have a look if you'd like. Additionally, using a framework such as FAISS would most probably improve processing time for the frame-to-frame calculation; however, this is only a fraction of the total processing time. As you very accurately point out, the video-to-video part can not benefit from FAISS as it is a CNN network. In general, IMO applying conceptual improvement in the search process (similar to our DnS work) is a more straightforward solution, rather than trying to optimize the current method.
